import os
import subprocess

import numpy as np

TESTS_DIR = os.path.dirname(os.path.realpath(__file__))
INPUT_DIR = os.path.join(TESTS_DIR, "data", "figure_him_matrix", "IN")
OUTPUT_DIR = os.path.join(TESTS_DIR, "data", "figure_him_matrix", "OUT")


def compare_npy(gen_out_path, expected):
    gene = np.load(gen_out_path)
    expe = np.load(expected)
    return np.testing.assert_array_equal(gene, expe)


def check_script_run_normally(result, gen_out_path, expected):
    assert result.returncode == 0, f"Runtime error: {result.stderr}"
    assert os.path.exists(gen_out_path), f"Output file {gen_out_path} isn't created"
    # assert compare_npy(gen_out_path, expected), f"Difference detected between {gen_out_path} and {expected}"
    compare_npy(gen_out_path, expected)


INPUT_NPY = INPUT_DIR + os.sep + "n_cells_250_pwd_sc_matrix.npy"
INPUT_ECSV = INPUT_DIR + os.sep + "unique_barcodes.ecsv"


def delete_paths(path_list: list) -> None:
    for p in path_list:
        if os.path.exists(p):
            os.remove(p)


def test_input():
    # Determine output file that should be generated by the script
    matrix_filename = "Fig_n_cells_250_pwd_sc_matrix_proximity_0.00-0.10.npy"
    png_filename = "Fig_n_cells_250_pwd_sc_matrix_proximity_0.00-0.10.png"
    nan_filename = "Fig_n_cells_250_pwd_sc_matrix_proximity_0.81-0.96_nan%.png"
    generated_png_path = os.path.join(INPUT_DIR, png_filename)
    generated_nan_path = os.path.join(INPUT_DIR, nan_filename)
    generated_matrix_path = os.path.join(INPUT_DIR, matrix_filename)
    expected_matrix_path = os.path.join(OUTPUT_DIR, matrix_filename)

    # Delete old files if exist to avoid conflict
    delete_paths([generated_png_path, generated_matrix_path, generated_nan_path])

    # Run script with CLI
    result = subprocess.run(
        [
            "figure_him_matrix",
            "-M",
            INPUT_NPY,
            "-B",
            INPUT_ECSV,
            "--mode",
            "proximity",
            "-O",
            INPUT_DIR,
        ],
        capture_output=True,
        text=True,
    )
    assert os.path.exists(generated_png_path)
    assert os.path.exists(generated_nan_path)
    check_script_run_normally(result, generated_matrix_path, expected_matrix_path)

    delete_paths([generated_png_path, generated_matrix_path, generated_nan_path])
