[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "traceratops"
version = "0.1.0"
description = "Toolbox for trace analysis"
readme = "README.md"
authors = [
    { name = "Marcelo Nollmann", email = "marcelo.nollmann@cbs.cnrs.fr" },
    { name = "Xavier Devos", email = "xavier.devos@cbs.cnrs.fr" },
]
license = { file = "LICENSE" }
keywords = []
dependencies = ["numpy", "matplotlib", "pandas", "astropy", "tqdm"]
requires-python = ">=3.9"

[project.optional-dependencies]
# When there is "for doc" comments
# --> think to duplicate to 'docs/requirements.txt'
dev = [
    "pytest",
    "sphinx",           # for doc
    "sphinx-rtd-theme", # for doc
    "sphinx-argparse",  # for doc
    "myst-parser",      # for doc
    "pre-commit",
]

[project.urls]
Homepage = "https://github.com/pyHi-M/traceratops"

[project.scripts]
trace_filter = "traceratops.trace_filter:main"

# [tool.setuptools]
# include-package-data = true

# [tool.setuptools.package-data]
# "path.to.files" = ["*.json"]
